### ISSUE TITLE
Why "data_2019-05-14.csv" can't be read by read_csv?

### ISSUE THREAD

**Issue by frankred3** [abichat/tidytuesday#2]
@abichat ,why" data_2019-05-14.csv  "  file can't be  read by read_csv  function :
>nobel_winners<-read_csv("data_2019-05-14.csv",col_types = "dccccdccDccccccDcc")
Warning: 22431 parsing failures.
row             col expected                                                                  actual                  file
  1 <!DOCTYPE html> a double <html lang="en">                                                        'data_2019-05-14.csv'
  2 <!DOCTYPE html> a double <head>                                                                  'data_2019-05-14.csv'
  3 <!DOCTYPE html> a double <meta charset="utf-8">                                                  'data_2019-05-14.csv'
  4 <!DOCTYPE html> a double <link rel="dns-prefetch" href="https://github.githubassets.com">        'data_2019-05-14.csv'
  5 <!DOCTYPE html> a double <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com"> 'data_2019-05-14.csv'
... ............... ........ ....................................................................... .....................
See problems(...) for more details.

Warning message:
Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 

I view the file in notpad,found that it's a **_html_** file but not a **_csv_** file.

**Comment by abichat** [comment]
I don't understand why you see it as a html file because it's a csv file in the repo as you can see [here](https://github.com/abichat/tidytuesday/blob/master/data/data_2019-05-14.csv) and [here](https://raw.githubusercontent.com/abichat/tidytuesday/master/data/data_2019-05-14.csv).
And I use `readr` 1.3.1
```
> library(tidyverse)
> nobel_winners <- read_csv("data/data_2019-05-14.csv",
+                           col_types = "dccccdccDccccccDcc")
> nobel_winners
# A tibble: 969 x 18
   prize_year category prize motivation prize_share laureate_id laureate_type full_name birth_date birth_city birth_country
        <dbl> <chr>    <chr> <chr>      <chr>             <dbl> <chr>         <chr>     <date>     <chr>      <chr>        
 1       1901 Chemist… The … "\"in rec… 1/1                 160 Individual    Jacobus … 1852-08-30 Rotterdam  Netherlands  
```

**Comment by frankred3** [comment]
Thank you , I found the reason, i download the file from the filelist page at  beginning , 
https://github.com/abichat/tidytuesday/blob/master/data/data_2019-05-14.csv
At last,  i open this file  in new page and download it from the "Raw" button, this time the file is right.

**Comment by abichat** [comment]
Good news
